import type { NextPage } from "next";
import Head from "next/head";
import { ChangeEvent, FormEvent, useRef, useState } from "react";
import Header from "../Components/Header";
import Library from "../Components/Library/Library";
import Main from "../Components/Main/Main";
import Search from "../Components/Search/Search";
import Sidebar from "../Components/Sidebar";
import TopSongs from "../Components/TopSongs/TopSongs";

const Home: NextPage = () => {
  const songRef = useRef<HTMLInputElement>(null);
  const [songName, setSongName] = useState("");
  const [activePage, setActivePage] = useState("home");

  const getName = (e: ChangeEvent<HTMLInputElement>) => {
    setSongName(e.target.value);
  };

  const searchForName = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    console.log(songRef.current?.value);
  };
  return (
    <div className="h-screen flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="flex h-full">
        <Sidebar setPage={setActivePage} />

        {(activePage === "home" && <Main />) ||
          (activePage === "search" && <Search />) ||
          (activePage === "lib" && <Library />)}

        <TopSongs />
      </div>

      {/* <main> */}
      {/*   <form onSubmit={searchForName}> */}
      {/*     <input */}
      {/*       type="text" */}
      {/*       placeholder="Search" */}
      {/*       ref={songRef} */}
      {/*       onChange={(e) => getName(e)} */}
      {/*     /> */}
      {/*     <input type="submit" /> */}
      {/*   </form> */}
      {/* </main> */}
    </div>
  );
};

export default Home;
