import type { NextPage } from "next";
import Head from "next/head";
import { ChangeEvent, FormEvent, useRef, useState } from "react";
import Header from "../Components/Header";
import Library from "../Components/Library/Library";
import Main from "../Components/Main/Main";
import Search from "../Components/Search/Search";
import Sidebar from "../Components/Sidebar";
import TopSongs from "../Components/TopSongs/TopSongs";

interface data {
  image: string;
  title: any;
  artist: string;
}

const Home = (props: { obj: data[]}) => {
  const [activePage, setActivePage] = useState("home");

	return (
    <div className="h-screen flex flex-col overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="flex h-full">
        <Sidebar setPage={setActivePage} />

        <div className="bg-gray-500 w-full pl-8 pr-2 py-4">
          {(activePage === "home" && <Main props={props.obj} />) ||
            (activePage === "search" && <Search />) ||
            (activePage === "lib" && <Library />)}
        </div>

        <TopSongs />
      </div>
    </div>
  );
};

export async function getServerSideProps() {
  let musicData = await fetch("http://localhost:3001/globals");
  const music = await musicData.json();

  let obj = [];
  for (let i = 0; i < music.length; i++) {
    obj.push({
      image: music[i].images?.background ? music[i].images.background : null,
      title: music[i].title,
      artist: music[i].subtitle,
    });
  }

  return {
    props: {
      obj,
    },
  };
}

export default Home;
